/**
 * FoodMenuService in Angular 19
 */
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class FoodMenuService {
  constructor() {}

  getFoodMenu(): any {
    return [
      {
        id: 1,
        name: 'maharaja-laddoo',
        title: 'Maharaja Laddoo',
        bestSeason: 'Winter',
        isNonVeg: false,
        ingredients: [
          {
            id: 1,
            name: 'Gram Flour',
            healthBenefits: 'Rich in protein and fiber',
          },
          {
            id: 2,
            name: 'Ghee',
            healthBenefits: 'Boosts energy and aids digestion',
          },
          { id: 3, name: 'Gudd & Jaggery', healthBenefits: 'Provides quick energy' },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Maharaja Laddoo Image',
            url: 'assets/images/menu/maharaja-laddoo/thumbnail.jpg',
          },
        ],
        description: 'A rich and traditional Indian sweet.',
        category: 'sweets',
        lifeInDays: 15,
        flavourType: 'non spicy',
        createdOn: new Date('2025-01-01'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'SMALL',
        price: '800',
        quantity: null,
        measurement: 'per Kg',
        addons: ['Extra Ghee', 'Dry Fruits'],
        discount: 10,
        days: 'Monday',
        type: 'Dish',
        availableToday: 'true',
        ratings: 4.8,
        foodItems: [
          {
            id: 1,
            name: 'Laddoo Piece',
            quantity: null,
            isRequired : true,
            availableToday: 'true',
            weight: '1 Kg',
            description: 'Soft and rich laddoo pieces.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Absolutely delicious!',
            userId: 101,
            userName: 'John Doe',
            userImage: 'https://example.com/john.jpg',
          },
          {
            id: 2,
            comment: 'Perfect for festivals.',
            userId: 102,
            userName: 'Jane Smith',
            userImage: 'https://example.com/jane.jpg',
          },
        ],
      },
      {
        id: 2,
        name: 'chole-poori',
        title: 'Spicy Chole Poori',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          {
            id: 1,
            name: 'Chickpeas',
            healthBenefits: 'High in protein and fiber',
          },
          { id: 2, name: 'Spices', healthBenefits: 'Boosts metabolism' },
          {
            id: 3,
            name: 'Wheat Flour',
            healthBenefits: 'Good source of carbs',
          },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Chole Poori Image',
            url: 'assets/images/menu/chole-poori/thumbnail.jpg',
          },
        ],
        description: `
🍛 Chole: Slow-cooked with aromatic spices, tangy tomatoes, and a hint of fresh coriander for a rich and hearty flavor.
🥙 Puri: Golden, fluffy, and perfectly crispy – made fresh with the finest whole wheat flour.`,
        category: 'breakfast',
        lifeInDays: 1,
        flavourType: 'spicy',
        createdOn: new Date('2025-01-02'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'Large',
        price: '120',
        quantity: 1,
        measurement: 'Plate',
        addons: ['Pickle', 'Curd'],
        discount: 5,
        days: 'Tuesday',
        type: 'Dish',
        availableToday: true,
        ratings: 4.5,
        foodItems: [
          {
            id: 1,
            name: 'Chole',
            quantity: null,
            isRequired : true,
            availableToday: 'true',
            weight: '300g',
            description: 'Spicy and flavorful chickpeas.',
          },
          {
            id: 2,
            name: 'Poori',
            quantity: 5,
            isRequired : true,
            availableToday: 'true',
            weight: null,
            description: 'Crispy and golden Oats Poori.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Great taste and fresh!',
            userId: 103,
            userName: 'Alice Brown',
            userImage: 'https://example.com/alice.jpg',
          },
          {
            id: 2,
            comment: 'Loved the spiciness.',
            userId: 104,
            userName: 'Bob Green',
            userImage: 'https://example.com/bob.jpg',
          },
        ],
      },
      {
        id: 3,
        name: 'royal-rajasthani-thali',
        title: 'Royal Rajasthani Thali',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Multiple Dishes', healthBenefits: 'Balanced meal' },
          { id: 2, name: 'Roti', healthBenefits: 'Good source of carbs' },
          { id: 3, name: 'Rice', healthBenefits: 'Provides energy' },
        ],
        region: 'Pan India',
        images: [
          {
            id: 1,
            name: 'Royal Thali Image',
            url: 'assets/images/menu/royal-rajasthani-thali/thumbnail.jpg',
          },
        ],
        description: 'A grand and wholesome meal.',
        category: 'thali',
        lifeInDays: 1,
        flavourType: 'non spicy',
        createdOn: new Date('2025-01-03'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        type: 'Dish',
        availableToday: true,
        size: 'MEDIUM',
        price: '350',
        quantity: 1,
        measurement: 'Plate',
        addons: ['Extra Curry', 'Dessert'],
        discount: 10,
        days: 'Wednesday',
        ratings: 4.9,
        foodItems: [
          {
            id: 1,
            name: 'Paneer Curry',
            quantity: null,
            weight: '200g',
            isRequired : true,
            availableToday: true,
            description: 'Rich and creamy paneer curry.',
          },
          {
            id: 2,
            name: 'Arahar Dal Tadka',
            quantity: null,
            isRequired : true,
            availableToday: true,
            weight: '150g',
            description: 'Light and flavorful arahar/channa daal',
          },
          {
            id: 3,
            name: 'Rice',
            quantity: null,
            isRequired : false,
            availableToday: true,
            weight: '200g',
            description: 'Steamed basmati rice.',
          },
          {
            id: 4,
            name: 'Desi Ghee Dipped Baati',
            quantity: 4,
            isRequired : true,
            availableToday: true,
            weight: null,
            description: 'Rounded crunchy baati, dipped in Ghee.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect for a full meal!',
            userId: 105,
            userName: 'Charlie Black',
            userImage: 'https://example.com/charlie.jpg',
          },
          {
            id: 2,
            comment: 'So many delicious dishes.',
            userId: 106,
            userName: 'Diana White',
            userImage: 'https://example.com/diana.jpg',
          },
        ],
      },
      {
        id: 4,
        name: 'veg-appe',
        title: 'Crispy Veg Appe',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Rice Flour', healthBenefits: 'Easy to digest' },
          { id: 2, name: 'Vegetables', healthBenefits: 'Rich in vitamins' },
          {
            id: 3,
            name: 'Spices',
            healthBenefits: 'Enhances taste and digestion',
          },
        ],
        region: 'South India',
        images: [
          {
            id: 1,
            name: 'Veg Appe Image',
            url: 'assets/images/menu/veg-appe/thumbnail.jpg',
          },
        ],
        description: 'A healthy and tasty snack.',
        category: 'breakfast',
        lifeInDays: 2,
        flavourType: 'spicy',
        createdOn: new Date('2025-01-04'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'SMALL',
        price: '100',
        quantity: 12,
        measurement: 'Plate',
        addons: ['Coconut Chutney', 'Sambar'],
        discount: 5,
        days: 'Thursday',
        type: 'Dish',
        availableToday: true,
        ratings: 4.6,
        foodItems: [
          {
            id: 1,
            name: 'Appe Pieces',
            quantity: 12,
            weight: null,
            description: 'Crispy and healthy snack.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect snack!',
            userId: 107,
            userName: 'Eve Blue',
            userImage: 'https://example.com/eve.jpg',
          },
          {
            id: 2,
            comment: 'Loved the chutney.',
            userId: 108,
            userName: 'Frank Red',
            userImage: 'https://example.com/frank.jpg',
          },
        ],
      },
      {
        id: 5,
        name: 'shahi-laddoo',
        title: 'Royal Shahi Laddoo',
        bestSeason: 'Winter',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Almonds', healthBenefits: 'Rich in healthy fats' },
          { id: 2, name: 'Milk', healthBenefits: 'Good source of calcium' },
          { id: 3, name: 'Honey', healthBenefits: 'Natural sweetener' },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Shahi Laddoo Image',
            url: 'assets/images/menu/shahi-laddoo/thumbnail.jpg',
          },
        ],
        description: 'A luxurious and healthy sweet.',
        category: 'sweets',
        lifeInDays: 10,
        flavourType: 'non spicy',
        createdOn: new Date('2025-01-04'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'LARGE',
        price: '1200',
        quantity: 1,
        measurement: 'per Kg',
        addons: ['Extra Honey', 'Dry Fruits'],
        type: 'Dish',
        availableToday: true,
        discount: 10,
        days: 'Friday',
        ratings: 4.6,
        foodItems: [
          {
            id: 1,
            name: 'Shahi Laddoo',
            quantity: null,
            weight: '1 Kg',
            description: 'Crispy and healthy snack.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect snack!',
            userId: 107,
            userName: 'Eve Blue',
            userImage: 'https://example.com/eve.jpg',
          },
          {
            id: 2,
            comment: 'Loved the chutney.',
            userId: 108,
            userName: 'Frank Red',
            userImage: 'https://example.com/frank.jpg',
          },
        ],
      },
      {
        id: 6,
        name: 'veg-sandwich',
        title: 'Crispy Sandwich',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Rice Flour', healthBenefits: 'Easy to digest' },
          { id: 2, name: 'Vegetables', healthBenefits: 'Rich in vitamins' },
          {
            id: 3,
            name: 'Spices',
            healthBenefits: 'Enhances taste and digestion',
          },
        ],
        region: 'Global',
        images: [
          {
            id: 1,
            name: 'Veg Appe Image',
            url: 'assets/images/menu/veg-sandwich/thumbnail.jpg',
          },
        ],
        description: 'A healthy and tasty snack.',
        category: 'breakfast',
        lifeInDays: 2,
        flavourType: 'spicy',
        createdOn: new Date('2025-01-04'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'MEDIUM',
        price: '95',
        quantity: 1,
        measurement: 'Plate',
        addons: ['Chutney'],
        discount: 5,
        days: 'Thursday',
        type: 'Dish',
        availableToday: true,
        ratings: 4.6,
        foodItems: [
          {
            id: 1,
            name: 'Grilled Bread Pieces',
            quantity: 4,
            weight: null,
            description: 'Crispy and healthy snack.',
          },
          {
            id: 2,
            name: 'Tomato Ketchup Sachet',
            quantity: 2,
            weight: null,
            description: 'Crispy and healthy snack.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect snack!',
            userId: 107,
            userName: 'Eve Blue',
            userImage: 'https://example.com/eve.jpg',
          },
          {
            id: 2,
            comment: 'Loved the chutney.',
            userId: 108,
            userName: 'Frank Red',
            userImage: 'https://example.com/frank.jpg',
          },
        ],
      },
      {
        id: 7,
        name: 'aloo-pyaj-paratha',
        title: 'Aloo Pyaj Paratha',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          {
            id: 1,
            name: 'Aloo (Potato)',
            healthBenefits: 'Rich in carbohydrates for energy',
          },
          {
            id: 2,
            name: 'Pyaj (Onion)',
            healthBenefits: 'Good source of antioxidants and fiber',
          },
          {
            id: 3,
            name: 'Whole Wheat Flour',
            healthBenefits: 'Rich in fiber for digestion',
          },
        ],
        region: 'North India',
        images: [
            {
              id: 1,
              name: 'Aloo Pyaaj Paratha',
              url: 'assets/images/menu/aloo-pyaj-paratha/thumbnail.jpg',
            },
          ],
        description:
          'Traditional North Indian delight made with love and fresh ingredients, perfect for breakfast or evening snacks.',
        category: 'breakfast',
        lifeInDays: 1,
        flavourType: 'mild spicy',
        createdOn: new Date(),
        isDeleted: false,
        lastUpdatedOn: new Date(),
        size: 'MEDIUM',
        price: '150',
        quantity: 1,
        measurement: 'Per Plate',
        addons: ['Red Sweet Chutney', 'Green Spicy Chutney'],
        discount: 0,
        type: 'Dish',
        availableToday: true,
        days: 'All Days',
        ratings: 0,
        foodItems: [
          {
            id: 1,
            name: 'Paratha',
            quantity: 2,
            weight: '200g',
            description:
              'Soft, flaky parathas with a savory potato and onion filling.',
          },
        ],
        comments: [],
      },
        {
          "id": 8,
          "name": "pao-bhaaji",
          "title": "Pao Bhaaji",
          "bestSeason": "All",
          "isNonVeg": false,
          "ingredients": [
            { "id": 1, "name": "Potatoes", "healthBenefits": "Rich in carbohydrates" },
            { "id": 2, "name": "Tomatoes", "healthBenefits": "High in Vitamin C" },
            { "id": 3, "name": "Spices", "healthBenefits": "Boosts metabolism" }
          ],
          "region": "West India",
          "images": [
            { "id": 2, "name": "Pao Bhaaji Image", "url": "assets/images/menu/pao-bhaaji/thumbnail.jpg" }
          ],
          "description": "A spicy and flavorful street food dish.",
          "category": "snacks",
          "lifeInDays": 1,
          "flavourType": "spicy",
          "createdOn": "2025-01-01T00:00:00.000Z",
          "isDeleted": false,
          "lastUpdatedOn": "2025-01-05T00:00:00.000Z",
          "size": "MEDIUM",
          "price": "150",
          "quantity": null,
          "measurement": "per plate",
          "addons": ["Extra Butter", "Pav"],
          "discount": 5,
          "days": "Tuesday",
          "type": "Dish",
          "availableToday": "true",
          "ratings": 4.7,
          "foodItems": [
            {
              "id": 2,
              "name": "Pao Bhaaji Plate",
              "quantity": null,
              "isRequired": true,
              "availableToday": "true",
              "weight": "250 g",
              "description": "Spicy Bhaaji served with buttery Pao."
            }
          ],
          "comments": [
            { "id": 1, "comment": "Loved the buttery pao!", "userId": 103, "userName": "Ravi Kumar", "userImage": "https://example.com/ravi.jpg" }
          ]
        },
        {
          "id": 9,
          "name": "methi-dhaniya-paratha",
          "title": "Methi Dhaniya Paratha",
          "bestSeason": "Winter",
          "isNonVeg": false,
          "ingredients": [
            { "id": 1, "name": "Fenugreek", "healthBenefits": "Good for digestion" },
            { "id": 2, "name": "Coriander", "healthBenefits": "Rich in antioxidants" },
            { "id": 3, "name": "Wheat Flour", "healthBenefits": "High in fiber" }
          ],
          "region": "North India",
          "images": [
            { "id": 3, "name": "Methi Dhaniya Paratha Image", "url": "assets/images/menu/methi-dhaniya-paratha/thumbnail.jpg" }
          ],
          "description": "Healthy flatbread with fenugreek and coriander.",
          "category": "breakfast",
          "lifeInDays": 2,
          "flavourType": "mild",
          "createdOn": "2025-01-01T00:00:00.000Z",
          "isDeleted": false,
          "lastUpdatedOn": "2025-01-05T00:00:00.000Z",
          "size": "LARGE",
          "price": "80",
          "quantity": null,
          "measurement": "per piece",
          "addons": ["Butter", "Curd"],
          "discount": 10,
          "days": "Wednesday",
          "type": "Dish",
          "availableToday": "true",
          "ratings": 4.6,
          "foodItems": [
            {
              "id": 3,
              "name": "Paratha Piece",
              "quantity": null,
              "isRequired": true,
              "availableToday": "true",
              "weight": "200 g",
              "description": "Soft and healthy paratha pieces."
            }
          ],
          "comments": [
            { "id": 1, "comment": "Perfectly cooked!", "userId": 104, "userName": "Neha Sharma", "userImage": "https://example.com/neha.jpg" }
          ]
        },
        {
          "id": 10,
          "name": "matar-mashroom-meal",
          "title": "Matar Mushroom Meal",
          "bestSeason": "Winter",
          "isNonVeg": false,
          "ingredients": [
            { "id": 1, "name": "Mushrooms", "healthBenefits": "Rich in protein" },
            { "id": 2, "name": "Green Peas", "healthBenefits": "High in fiber" },
            { "id": 3, "name": "Rice", "healthBenefits": "Good source of carbohydrates" }
          ],
          "region": "North India",
          "images": [
            { "id": 5, "name": "Matar Mushroom Meal Image", "url": "assets/images/menu/matar-mushroom-meal/thumbnail.jpg" }
          ],
          "description": "A hearty meal with mushrooms and peas in a creamy curry.",
          "category": "thali",
          "lifeInDays": 1,
          "flavourType": "spicy",
          "createdOn": "2025-01-01T00:00:00.000Z",
          "isDeleted": false,
          "lastUpdatedOn": "2025-01-05T00:00:00.000Z",
          "size": "LARGE",
          "price": "200",
          "quantity": null,
          "measurement": "per meal",
          "addons": ["Raita", "Papad"],
          "discount": 12,
          "days": "Friday",
          "type": "Dish",
          "availableToday": "true",
          "ratings": 4.6,
          "foodItems": [
            {
              "id": 5,
              "name": "Matar Mushroom Curry with Rice",
              "quantity": null,
              "isRequired": true,
              "availableToday": "true",
              "weight": "400 g",
              "description": "Flavorful curry served with steamed rice."
            }
          ],
          "comments": [
            { "id": 1, "comment": "Delicious and filling!", "userId": 106, "userName": "Priya Singh", "userImage": "https://example.com/priya.jpg" }
          ]
        }
      ]      
  }
}
