/**
 * FoodMenuService in Angular 19
 */
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class FoodMenuService {
  constructor() {}

  getFoodMenu(): any {
    return [
      {
        id: 1,
        name: 'maharaja-laddoo',
        title: 'Maharaja Laddoo',
        bestSeason: 'Winter',
        isNonVeg: false,
        ingredients: [
          {
            id: 1,
            name: 'Gram Flour',
            healthBenefits: 'Rich in protein and fiber',
          },
          {
            id: 2,
            name: 'Ghee',
            healthBenefits: 'Boosts energy and aids digestion',
          },
          {
            id: 3,
            name: 'Gudd & Jaggery',
            healthBenefits: 'Provides quick energy',
          },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Maharaja Laddoo Image',
            url: 'assets/images/product/maharaja-laddoo.jpg',
          },
        ],
        description: 'A rich and traditional Indian sweet.',
        category: 'sweets',
        lifeInDays: 15,
        flavourType: 'non spicy',
        createdOn: new Date('2025-01-01'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'SMALL',
        price: '800',
        quantity: null,
        measurement: 'per Kg',
        addons: ['Extra Ghee', 'Dry Fruits'],
        discount: 10,
        days: 'Monday',
        type: 'Dish',
        availableToday: 'true',
        ratings: 4.8,
        foodItems: [
          {
            id: 1,
            name: 'Laddoo Piece',
            quantity: null,
            isRequired: true,
            availableToday: 'true',
            weight: '1 Kg',
            description: 'Soft and rich laddoo pieces.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Absolutely delicious!',
            userId: 101,
            userName: 'John Doe',
            userImage: 'https://example.com/john.jpg',
          },
          {
            id: 2,
            comment: 'Perfect for festivals.',
            userId: 102,
            userName: 'Jane Smith',
            userImage: 'https://example.com/jane.jpg',
          },
        ],
      },
      {
        id: 2,
        name: 'chole-poori',
        title: 'Spicy Chole Poori',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          {
            id: 1,
            name: 'Chickpeas',
            healthBenefits: 'High in protein and fiber',
          },
          { id: 2, name: 'Spices', healthBenefits: 'Boosts metabolism' },
          {
            id: 3,
            name: 'Wheat Flour',
            healthBenefits: 'Good source of carbs',
          },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Chole Poori Image',
            url: 'assets/images/product/chole-poori.jpg',
          },
        ],
        description: `
🍛 Chole: Slow-cooked with aromatic spices, tangy tomatoes, and a hint of fresh coriander for a rich and hearty flavor.
🥙 Puri: Golden, fluffy, and perfectly crispy – made fresh with the finest whole wheat flour.`,
        category: 'breakfast',
        lifeInDays: 1,
        flavourType: 'spicy',
        createdOn: new Date('2025-01-02'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'Large',
        price: 169,
        quantity: 5,
        measurement: 'Plate',
        addons: ['Pickle', 'Curd'],
        discount: 5,
        days: 'Tuesday',
        type: 'Dish',
        availableToday: true,
        ratings: 4.5,
        foodItems: [
          {
            id: 1,
            name: 'Chole',
            quantity: null,
            isRequired: true,
            availableToday: 'true',
            weight: '300g',
            description: 'Spicy and flavorful chickpeas.',
          },
          {
            id: 2,
            name: 'Poori',
            quantity: 5,
            isRequired: true,
            availableToday: 'true',
            weight: null,
            description: 'Crispy and golden Oats Poori.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Great taste and fresh!',
            userId: 103,
            userName: 'Alice Brown',
            userImage: 'https://example.com/alice.jpg',
          },
          {
            id: 2,
            comment: 'Loved the spiciness.',
            userId: 104,
            userName: 'Bob Green',
            userImage: 'https://example.com/bob.jpg',
          },
        ],
      },
      {
        id: 3,
        name: 'royal-rajasthani-thali',
        title: 'Royal Rajasthani Thali',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Multiple Dishes', healthBenefits: 'Balanced meal' },
          { id: 2, name: 'Roti', healthBenefits: 'Good source of carbs' },
          { id: 3, name: 'Rice', healthBenefits: 'Provides energy' },
        ],
        region: 'Pan India',
        images: [
          {
            id: 1,
            name: 'Royal Thali Image',
            url: 'assets/images/product/royal-rajasthani-thali.jpg',
          },
        ],
        description: 'A grand and wholesome meal.',
        category: 'thali',
        lifeInDays: 1,
        flavourType: 'non spicy',
        createdOn: new Date('2025-01-03'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        type: 'Dish',
        availableToday: true,
        size: 'MEDIUM',
        price: 329,
        quantity: 1,
        measurement: 'Plate',
        addons: ['Extra Curry', 'Dessert'],
        discount: 10,
        days: 'Wednesday',
        ratings: 4.9,
        foodItems: [
          {
            id: 1,
            name: 'Paneer Curry',
            quantity: null,
            weight: '200g',
            isRequired: true,
            availableToday: true,
            description: 'Rich and creamy paneer curry.',
          },
          {
            id: 2,
            name: 'Arahar Dal Tadka',
            quantity: null,
            isRequired: true,
            availableToday: true,
            weight: '150g',
            description: 'Light and flavorful arahar/channa daal',
          },
          {
            id: 3,
            name: 'Rice',
            quantity: null,
            isRequired: false,
            availableToday: true,
            weight: '200g',
            description: 'Steamed basmati rice.',
          },
          {
            id: 4,
            name: 'Desi Ghee Dipped Baati',
            quantity: 4,
            isRequired: true,
            availableToday: true,
            weight: null,
            description: 'Rounded crunchy baati, dipped in Ghee.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect for a full meal!',
            userId: 105,
            userName: 'Charlie Black',
            userImage: 'https://example.com/charlie.jpg',
          },
          {
            id: 2,
            comment: 'So many delicious dishes.',
            userId: 106,
            userName: 'Diana White',
            userImage: 'https://example.com/diana.jpg',
          },
        ],
      },
      {
        id: 4,
        name: 'veg-appe',
        title: 'Crispy Veg Appe',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Rice Flour', healthBenefits: 'Easy to digest' },
          { id: 2, name: 'Vegetables', healthBenefits: 'Rich in vitamins' },
          {
            id: 3,
            name: 'Spices',
            healthBenefits: 'Enhances taste and digestion',
          },
        ],
        region: 'South India',
        images: [
          {
            id: 1,
            name: 'Veg Appe Image',
            url: 'assets/images/product/veg-appe.jpg',
          },
        ],
        description: 'A healthy and tasty snack.',
        category: 'breakfast',
        lifeInDays: 2,
        flavourType: 'spicy',
        createdOn: new Date('2025-01-04'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'SMALL',
        price: '100',
        quantity: 12,
        measurement: 'Plate',
        addons: ['Coconut Chutney', 'Sambar'],
        discount: 5,
        days: 'Thursday',
        type: 'Dish',
        availableToday: true,
        ratings: 4.6,
        foodItems: [
          {
            id: 1,
            name: 'Appe Pieces',
            quantity: 12,
            weight: null,
            description: 'Crispy and healthy snack.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect snack!',
            userId: 107,
            userName: 'Eve Blue',
            userImage: 'https://example.com/eve.jpg',
          },
          {
            id: 2,
            comment: 'Loved the chutney.',
            userId: 108,
            userName: 'Frank Red',
            userImage: 'https://example.com/frank.jpg',
          },
        ],
      },
      {
        id: 5,
        name: 'shahi-laddoo',
        title: 'Royal Shahi Laddoo',
        bestSeason: 'Winter',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Almonds', healthBenefits: 'Rich in healthy fats' },
          { id: 2, name: 'Milk', healthBenefits: 'Good source of calcium' },
          { id: 3, name: 'Honey', healthBenefits: 'Natural sweetener' },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Shahi Laddoo Image',
            url: 'assets/images/product/shahi-laddoo.jpg',
          },
        ],
        description: 'A luxurious and healthy sweet.',
        category: 'sweets',
        lifeInDays: 10,
        flavourType: 'non spicy',
        createdOn: new Date('2025-01-04'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'LARGE',
        price: '1200',
        quantity: 1,
        measurement: 'per Kg',
        addons: ['Extra Honey', 'Dry Fruits'],
        type: 'Dish',
        availableToday: true,
        discount: 10,
        days: 'Friday',
        ratings: 4.6,
        foodItems: [
          {
            id: 1,
            name: 'Shahi Laddoo',
            quantity: null,
            weight: '1 Kg',
            description: 'Crispy and healthy snack.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect snack!',
            userId: 107,
            userName: 'Eve Blue',
            userImage: 'https://example.com/eve.jpg',
          },
          {
            id: 2,
            comment: 'Loved the chutney.',
            userId: 108,
            userName: 'Frank Red',
            userImage: 'https://example.com/frank.jpg',
          },
        ],
      },
      {
        id: 6,
        name: 'veg-sandwich',
        title: 'Crispy Sandwich',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Rice Flour', healthBenefits: 'Easy to digest' },
          { id: 2, name: 'Vegetables', healthBenefits: 'Rich in vitamins' },
          {
            id: 3,
            name: 'Spices',
            healthBenefits: 'Enhances taste and digestion',
          },
        ],
        region: 'Global',
        images: [
          {
            id: 1,
            name: 'Veg Appe Image',
            url: 'assets/images/product/veg-sandwich.jpg',
          },
        ],
        description: 'A healthy and tasty snack.',
        category: 'breakfast',
        lifeInDays: 2,
        flavourType: 'spicy',
        createdOn: new Date('2025-01-04'),
        isDeleted: false,
        lastUpdatedOn: new Date('2025-01-05'),
        size: 'MEDIUM',
        price: 120,
        quantity: 4,
        measurement: 'Plate',
        addons: ['Chutney'],
        discount: 5,
        days: 'Thursday',
        type: 'Dish',
        availableToday: true,
        ratings: 4.6,
        foodItems: [
          {
            id: 1,
            name: 'Grilled Bread Pieces',
            quantity: 4,
            weight: null,
            description: 'Crispy and healthy snack.',
          },
          {
            id: 2,
            name: 'Tomato Ketchup Sachet',
            quantity: 2,
            weight: null,
            description: 'Crispy and healthy snack.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Perfect snack!',
            userId: 107,
            userName: 'Eve Blue',
            userImage: 'https://example.com/eve.jpg',
          },
          {
            id: 2,
            comment: 'Loved the chutney.',
            userId: 108,
            userName: 'Frank Red',
            userImage: 'https://example.com/frank.jpg',
          },
        ],
      },
      {
        id: 7,
        name: 'aloo-pyaj-paratha',
        title: 'Aloo Pyaj Paratha',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          {
            id: 1,
            name: 'Aloo (Potato)',
            healthBenefits: 'Rich in carbohydrates for energy',
          },
          {
            id: 2,
            name: 'Pyaj (Onion)',
            healthBenefits: 'Good source of antioxidants and fiber',
          },
          {
            id: 3,
            name: 'Whole Wheat Flour',
            healthBenefits: 'Rich in fiber for digestion',
          },
        ],
        region: 'North India',
        images: [
          {
            id: 1,
            name: 'Aloo Pyaaj Paratha',
            url: 'assets/images/product/aloo-pyaj-paratha.jpg',
          },
        ],
        description:
          'Traditional North Indian delight made with love and fresh ingredients, perfect for breakfast or evening snacks.',
        category: 'breakfast',
        lifeInDays: 1,
        flavourType: 'mild spicy',
        createdOn: new Date(),
        isDeleted: false,
        lastUpdatedOn: new Date(),
        size: 'LARGE',
        price: 129,
        quantity: 2,
        measurement: 'Per Plate',
        addons: ['Red Sweet Chutney', 'Green Spicy Chutney'],
        discount: 0,
        type: 'Dish',
        availableToday: true,
        days: 'All Days',
        ratings: 0,
        foodItems: [
          {
            id: 1,
            name: 'Paratha',
            quantity: 2,
            weight: '200g',
            description:
              'Soft, flaky parathas with a savory potato and onion filling.',
          },
        ],
        comments: [],
      },
      {
        id: 8,
        name: 'pao-bhaaji',
        title: 'Pao Bhaaji',
        bestSeason: 'All',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Potatoes', healthBenefits: 'Rich in carbohydrates' },
          { id: 2, name: 'Tomatoes', healthBenefits: 'High in Vitamin C' },
          { id: 3, name: 'Spices', healthBenefits: 'Boosts metabolism' },
        ],
        region: 'West India',
        images: [
          {
            id: 2,
            name: 'Pao Bhaaji Image',
            url: 'assets/images/product/pao-bhaaji.jpg',
          },
        ],
        description: 'A spicy and flavorful street food dish.',
        category: 'snacks',
        lifeInDays: 1,
        flavourType: 'spicy',
        createdOn: '2025-01-01T00:00:00.000Z',
        isDeleted: false,
        lastUpdatedOn: '2025-01-05T00:00:00.000Z',
        size: 'LARGE',
        price: 219,
        quantity: null,
        measurement: 'per plate',
        addons: ['Extra Butter', 'Pav'],
        discount: 5,
        days: 'Tuesday',
        type: 'Dish',
        availableToday: 'true',
        ratings: 4.7,
        foodItems: [
          {
            id: 2,
            name: 'Pao Bhaaji Plate',
            quantity: null,
            isRequired: true,
            availableToday: 'true',
            weight: '250 g',
            description: 'Spicy Bhaaji served with buttery Pao.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Loved the buttery pao!',
            userId: 103,
            userName: 'Ravi Kumar',
            userImage: 'https://example.com/ravi.jpg',
          },
        ],
      },
      {
        id: 10,
        name: 'matar-mashroom-meal',
        title: 'Matar Mushroom Meal',
        bestSeason: 'Winter',
        isNonVeg: false,
        ingredients: [
          { id: 1, name: 'Mushrooms', healthBenefits: 'Rich in protein' },
          { id: 2, name: 'Green Peas', healthBenefits: 'High in fiber' },
          {
            id: 3,
            name: 'Rice',
            healthBenefits: 'Good source of carbohydrates',
          },
        ],
        region: 'North India',
        images: [
          {
            id: 5,
            name: 'Matar Mushroom Meal Image',
            url: 'assets/images/product/matar-mushroom-meal.jpg',
          },
        ],
        description: 'A hearty meal with mushrooms and peas in a creamy curry.',
        category: 'thali',
        lifeInDays: 1,
        flavourType: 'spicy',
        createdOn: '2025-01-01T00:00:00.000Z',
        isDeleted: false,
        lastUpdatedOn: '2025-01-05T00:00:00.000Z',
        size: 'LARGE',
        price: 239,
        quantity: null,
        measurement: 'per meal',
        addons: ['Raita', 'Papad'],
        discount: 12,
        days: 'Friday',
        type: 'Dish',
        availableToday: 'true',
        ratings: 4.6,
        foodItems: [
          {
            id: 5,
            name: 'Matar Mushroom Curry with Rice',
            quantity: null,
            isRequired: true,
            availableToday: 'true',
            weight: '400 g',
            description: 'Flavorful curry served with steamed rice.',
          },
        ],
        comments: [
          {
            id: 1,
            comment: 'Delicious and filling!',
            userId: 106,
            userName: 'Priya Singh',
            userImage: 'https://example.com/priya.jpg',
          },
        ],
      },
      {
        "id": 12,
        "name": "shahi-thali",
        "title": "Shahi Thali",
        "bestSeason": "All Seasons",
        "isNonVeg": false,
        "ingredients": [
          { "id": 1, "name": "Paneer", "healthBenefits": "Rich in protein and calcium" },
          { "id": 2, "name": "Whole Wheat", "healthBenefits": "High in fiber" },
          { "id": 3, "name": "Black Lentils", "healthBenefits": "Good source of iron and protein" },
          { "id": 4, "name": "Butter", "healthBenefits": "Provides essential fats" },
          { "id": 5, "name": "Onion", "healthBenefits": "Rich in antioxidants" },
          { "id": 6, "name": "Spices", "healthBenefits": "Boosts metabolism" }
        ],
        "region": "North India",
        "images": [
          {
            "id": 6,
            "name": "Shahi Thali Image",
            "url": "assets/images/product/shahi-thali.jpg"
          }
        ],
        "description": "A luxurious thali featuring stuffed parathas, creamy dal makhani, paneer curry, pickle, and accompaniments.",
        "category": "thali",
        "lifeInDays": 1,
        "flavourType": "spicy",
        "createdOn": "2025-01-01T00:00:00.000Z",
        "isDeleted": false,
        "lastUpdatedOn": "2025-01-05T00:00:00.000Z",
        "size": "LARGE",
        "price": 319,
        "quantity": null,
        "measurement": "per thali",
        "addons": ["Extra Butter", "Raita"],
        "discount": 10,
        "days": "Sunday",
        "type": "Dish",
        "availableToday": "true",
        "ratings": 4.7,
        "foodItems": [
          {
            "id": 7,
            "name": "Stuffed Paratha",
            "quantity": "2 pieces",
            "isRequired": true,
            "availableToday": "true",
            "weight": "200 g",
            "description": "Soft parathas stuffed with spiced fillings."
          },
          {
            "id": 8,
            "name": "Dal Makhani",
            "quantity": "1 bowl",
            "isRequired": true,
            "availableToday": "true",
            "weight": "200 g",
            "description": "Creamy and flavorful black lentil curry."
          },
          {
            "id": 9,
            "name": "Paneer Curry",
            "quantity": "1 bowl",
            "isRequired": true,
            "availableToday": "true",
            "weight": "200 g",
            "description": "Rich paneer curry with a spicy kick."
          },
          {
            "id": 10,
            "name": "Pickle & Onion",
            "quantity": null,
            "isRequired": true,
            "availableToday": "true",
            "weight": null,
            "description": "Traditional Indian pickle and fresh onion slices."
          },
          {
            "id": 11,
            "name": "Gulab Jamun",
            "quantity": "1 piece",
            "isRequired": true,
            "availableToday": "true",
            "weight": "50 g",
            "description": "A sweet and syrupy dessert."
          }
        ],
        "comments": [
          {
            "id": 1,
            "comment": "Amazing thali, loved the parathas!",
            "userId": 201,
            "userName": "Amit Verma",
            "userImage": "https://example.com/amit.jpg"
          },
          {
            "id": 2,
            "comment": "Perfect blend of flavors. Will order again.",
            "userId": 202,
            "userName": "Sneha Kapoor",
            "userImage": "https://example.com/sneha.jpg"
          }
        ]
      }, 
      {
        "id": 13,
        "name": "aloo-matar-kachori",
        "title": "Aloo Matar Kachori",
        "bestSeason": "All Seasons",
        "isNonVeg": false,
        "ingredients": [
          { "id": 1, "name": "Potatoes", "healthBenefits": "Rich in carbohydrates and potassium" },
          { "id": 2, "name": "Green Peas", "healthBenefits": "High in fiber and protein" },
          { "id": 3, "name": "Whole Wheat Flour", "healthBenefits": "Rich in fiber and nutrients" },
          { "id": 4, "name": "Spices", "healthBenefits": "Boosts digestion and adds flavor" },
          { "id": 5, "name": "Oil", "healthBenefits": "Provides essential fats" }
        ],
        "region": "North India",
        "images": [
          {
            "id": 7,
            "name": "Aloo Matar Kachori Image",
            "url": "assets/images/product/aloo-matar-kachori.jpg"
          }
        ],
        "description": "Crispy and flaky kachoris stuffed with a spicy potato and green pea mixture, served with chutney.",
        "category": "snacks",
        "lifeInDays": 1,
        "flavourType": "spicy",
        "createdOn": "2025-01-01T00:00:00.000Z",
        "isDeleted": false,
        "lastUpdatedOn": "2025-01-05T00:00:00.000Z",
        "size": "MEDIUM",
        "price": 189,
        "quantity": 4,
        "measurement": "per plate",
        "addons": ["Extra Chutney", "Curd"],
        "discount": 5,
        "days": "Tuesday",
        "type": "Dish",
        "availableToday": "true",
        "ratings": 4.5,
        "foodItems": [
          {
            "id": 12,
            "name": "Aloo Matar Kachori",
            "quantity": "3 pieces",
            "isRequired": true,
            "availableToday": "true",
            "weight": "250 g",
            "description": "Golden and crispy kachoris stuffed with a flavorful potato and pea mixture."
          },
          {
            "id": 13,
            "name": "Tamarind Chutney",
            "quantity": "1 bowl",
            "isRequired": true,
            "availableToday": "true",
            "weight": "50 g",
            "description": "Sweet and tangy tamarind chutney for dipping."
          }
        ],
        "comments": [
          {
            "id": 1,
            "comment": "Perfectly crispy and tasty!",
            "userId": 301,
            "userName": "Ravi Sharma",
            "userImage": "https://example.com/ravi.jpg"
          },
          {
            "id": 2,
            "comment": "Loved the stuffing, very flavorful.",
            "userId": 302,
            "userName": "Meera Jain",
            "userImage": "https://example.com/meera.jpg"
          }
        ]
      },  
      {
        "id": 14,
        "name": "methi-dhaniya-paratha",
        "title": "Methi Dhaniya Paratha",
        "bestSeason": "Winter",
        "isNonVeg": false,
        "ingredients": [
          { "id": 1, "name": "Fresh Fenugreek Leaves (Methi)", "healthBenefits": "Rich in vitamins and fiber" },
          { "id": 2, "name": "Coriander Leaves (Dhaniya)", "healthBenefits": "Boosts immunity and adds freshness" },
          { "id": 3, "name": "Whole Wheat Flour", "healthBenefits": "Rich in fiber and nutrients" },
          { "id": 4, "name": "Spices", "healthBenefits": "Enhances flavor and aids digestion" },
          { "id": 5, "name": "Ghee", "healthBenefits": "Boosts energy and adds flavor" }
        ],
        "region": "North India",
        "images": [
          {
            "id": 8,
            "name": "Methi Dhaniya Paratha Image",
            "url": "assets/images/product/methi-dhaniya-paratha.jpg"
          }
        ],
        "description": "Soft and flavorful parathas made with fresh fenugreek and coriander leaves, served with creamy dahi.",
        "category": "breakfast",
        "lifeInDays": 1,
        "flavourType": "mild spicy",
        "createdOn": "2025-01-01T00:00:00.000Z",
        "isDeleted": false,
        "lastUpdatedOn": "2025-01-05T00:00:00.000Z",
        "size": "LARGE",
        "price": 109,
        "quantity": 2,
        "measurement": "per plate",
        "addons": ["Butter", "Pickle"],
        "discount": 8,
        "days": "Sunday",
        "type": "Dish",
        "availableToday": "true",
        "ratings": 4.7,
        "foodItems": [
          {
            "id": 14,
            "name": "Methi Dhaniya Paratha",
            "quantity": "2 pieces",
            "isRequired": true,
            "availableToday": "true",
            "weight": "200 g",
            "description": "Freshly made parathas with the goodness of methi and dhaniya."
          },
          {
            "id": 15,
            "name": "Dahi (Yogurt)",
            "quantity": "1 bowl",
            "isRequired": true,
            "availableToday": "true",
            "weight": "100 g",
            "description": "Thick and creamy yogurt served as a side."
          }
        ],
        "comments": [
          {
            "id": 1,
            "comment": "Perfect winter breakfast, very fresh and tasty!",
            "userId": 401,
            "userName": "Anjali Verma",
            "userImage": "https://example.com/anjali.jpg"
          },
          {
            "id": 2,
            "comment": "The parathas were so soft and the dahi was creamy. Loved it!",
            "userId": 402,
            "userName": "Rahul Mehta",
            "userImage": "https://example.com/rahul.jpg"
          }
        ]
      }
                   
    ];
  }
}
